### ISSUE TITLE
xSqlServerRole cannot detect NT AUTHORITY\SYSTEM as sysadmin

### ISSUE THREAD

**Issue by jrudley** [PowerShell/xSQLServer#188] opened 2016-11-10 19:14 UTC
I am trying to make sure NT AUTHORITY\SYSTEM is not part of the sysadmin role

VERBOSE: [SQL1]: LCM:  [ Start  Set      ]
VERBOSE: [SQL1]: LCM:  [ Start  Resource ]  [[xSQLServerRole]removeSysadmin]
VERBOSE: [SQL1]: LCM:  [ Start  Test     ]  [[xSQLServerRole]removeSysadmin]
VERBOSE: [SQL1]:                            [[xSQLServerRole]removeSysadmin] Testing SQL roles for login NT AUTHORITY\SYSTEM
VERBOSE: [SQL1]:                            [[xSQLServerRole]removeSysadmin] 2016-11-10_13-12-40: Connected to SQL sql1\inst1
VERBOSE: [SQL1]:                            [[xSQLServerRole]removeSysadmin] Getting SQL Server roles for NT AUTHORITY\SYSTEM on SQL Server sql1.
VERBOSE: [SQL1]:                            [[xSQLServerRole]removeSysadmin] 2016-11-10_13-12-40:  is absent in SQL role name sysadmin
VERBOSE: [SQL1]: LCM:  [ End    Test     ]  [[xSQLServerRole]removeSysadmin]  in 0.0310 seconds.
VERBOSE: [SQL1]: LCM:  [ Skip   Set      ]  [[xSQLServerRole]removeSysadmin]
VERBOSE: [SQL1]: LCM:  [ End    Resource ]  [[xSQLServerRole]removeSysadmin]
VERBOSE: [SQL1]: LCM:  [ End    Set      ]
VERBOSE: [SQL1]: LCM:  [ End    Set      ]    in  0.0780 seconds.

It is reporting absent when it has the sysadmin role assigned.

**Comment by jrudley** [comment] 2016-11-10 19:49
Quick glance, think I found the issue. 
$membersInRole.Contains($name) $name should be $loginName in the helper function for confirm-sqlserverrole

**Comment by johlju** [comment] 2016-11-10 20:57
@luigilink Would you be so kind to verify and solve this in PR #154 maybe?

**Comment by johlju** [comment] 2016-11-10 21:05
@luigilink On the other hand we might need an entire new PR for it, since the tests does not catch this error, this will be a bigger undertaking than a typo. We need to make sure to not mock the entire Confirm-SQLServerRole function. Same with Add-, and Remove-SQLServerRole functions. To much logic is being left untested :/
What do you guys think?

And @jrudley, thanks for catching this one!

**Comment by luigilink** [comment] 2016-11-11 11:20
I can add this issue in PR #154 or create a new PR, as you whish 😄

**Comment by johlju** [comment] 2016-11-11 13:50
@luigilink You may do whatever suits you, and only if you have the time :smile:

If you want your present PR to go thru review and merged faster then I would create a new PR for this.

**Comment by wickedave** [comment] 2017-01-12 16:34
Is there any new status on this? I'm facing the same problem.

**Comment by johlju** [comment] 2017-01-14 14:22
Sorry to say that this is not solved yet.

**Comment by pmcevoy** [comment] 2017-02-13 13:48
Is this problem present for windows groups?  I'm seeing  

```
VERBOSE: [TESTEZE-GM4AMLI]: LCM:  [ Start  Test     ]  [[xSQLServerRole]EZETOP\Domain Admins]
VERBOSE: [TESTEZE-GM4AMLI]:                            [[xSQLServerRole]EZETOP\Domain Admins] Testing SQL roles for login EZETOP\Domain Admins
VERBOSE: [TESTEZE-GM4AMLI]:                            [[xSQLServerRole]EZETOP\Domain Admins] 2017-02-13_13-41-05: Connected to SQL .
VERBOSE: [TESTEZE-GM4AMLI]:                            [[xSQLServerRole]EZETOP\Domain Admins] Getting SQL Server roles for EZETOP\Domain Admins on SQL Server ..
VERBOSE: [TESTEZE-GM4AMLI]:                            [[xSQLServerRole]EZETOP\Domain Admins] 2017-02-13_13-41-05:  is absent in SQL role name sysadmin
VERBOSE: [TESTEZE-GM4AMLI]:                            [[xSQLServerRole]EZETOP\Domain Admins] 2017-02-13_13-41-05: String value for property Ensure does not match. Current state is 'Absent' and Desired state is 'Present'
VERBOSE: [TESTEZE-GM4AMLI]: LCM:  [ End    Test     ]  [[xSQLServerRole]EZETOP\Domain Admins] False in 0.0240 seconds.
VERBOSE: [TESTEZE-GM4AMLI]: LCM:  [ End    Resource ]  [[xSQLServerRole]EZETOP\Domain Admins]
```

When SSMS clearly shows the group was added to the role

**Comment by johlju** [comment] 2017-02-13 17:38
Though it could be spaces in the name that made it fail. But no, I tested and it worked for me.

The following line seems wrong. 

```
VERBOSE: [TESTEZE-GM4AMLI]:                            [[xSQLServerRole]EZETOP\Domain Admins] 2017-02-13_13-41-05:  is absent in SQL role name sysadmin
```
$LoginName is nothing when this line is called.
https://github.com/PowerShell/xSQLServer/blob/dev/xSQLServerHelper.psm1#L1060

```
New-VerboseMessage -Message "$LoginName is absent in SQL role name $currentServerRole"
```

$LoginName should be the value in `-Name` parameter.

Could you post your configuration so I can test it?

**Comment by pmcevoy** [comment] 2017-02-13 17:42
Sure I also added it to https://github.com/PowerShell/xSQLServer/issues/371#issuecomment-279380545 in case someone searches closed issues:

```
            @(
                "EZETOP\Developers", 
                "EZETOP\SG-QA", 
                "EZETOP\Domain Admins", 
                "BUILTIN\Administrators"
            ) | %{
            xSQLServerLogin $_ {
                DependsOn = @("[xSqlServerSetup]RDBMS")
                Name = $_
                Ensure = "Present"
                SQLServer = "."
                SQLInstanceName = "MSSQLSERVER"
                LoginType = "WindowsGroup"
            }

            xSQLServerRole $_ {
                DependsOn = @(("[xSQLServerLogin]" + $_))
                Ensure = "Present"
                Name = $_
                SQLServer = "."
                SQLInstanceName = "MSSQLSERVER"
                ServerRole = "sysadmin"
            } 
        }
```

**Comment by johlju** [comment] 2017-02-13 18:09
Okej, strange. Having `xSQLServerLogin $_` and `xSQLServerRole $_` (same resource block description) the configuration was able to compile, but crashed the WMI when I tried to apply the configuration.
Changing the configuration slightly made it not crash the WMI and did correctly add the logins to the sysadmin server role (also had to modify if to work with my config)

```
            @(
                "COMPANY\SQL Administrators", 
                "COMPANY\Domain Admins", 
                "BUILTIN\Administrators"
            ) | %{
                    xSQLServerLogin "Login$($currentSqlInstance)-$_" {
                        DependsOn = @("[xSQLServerSetup]Install$($currentSqlInstance)Instance")
                        Name = $_
                        Ensure = "Present"
                        SQLServer = "."
                        SQLInstanceName = $currentSqlInstance
                        LoginType = "WindowsGroup"
                    }

                    xSQLServerRole "ServerRole$($currentSqlInstance)-$_" {
                        DependsOn = @(("[xSQLServerLogin]Login$($currentSqlInstance)-" + $_))
                        Ensure = "Present"
                        Name = $_
                        SQLServer = "."
                        SQLInstanceName = $currentSqlInstance
                        ServerRole = "sysadmin"
                } 
            }
```

**Comment by johlju** [comment] 2017-02-13 18:24
@pmcevoy I can reproduce your problem. My code above, does it make any difference? What OS, WMF version are you on?

**Comment by johlju** [comment] 2017-02-13 18:25
@pmcevoy Typo, I meant to say that I can't reproduce your problem.

**Comment by pmcevoy** [comment] 2017-02-14 09:35
Hi Johan - sorry about delayed reply: I think we are in different TZs, so I had left office before your reply got in.   

As per your suggestion, I updated my resource names to be quoted, and to add a prepend ("Login" / "ServerRole") but this does not seem to have made a difference.    

```
        @(
            "COMPANYP\Developers", 
            "COMPANY\SG-QA", 
            "COMPANY\Domain Admins", 
            "BUILTIN\Administrators"
        ) | %{
            xSQLServerLogin "Login$_" {
                DependsOn = @("[xSqlServerSetup]RDBMS")
                Name = $_
                Ensure = "Present"
                SQLServer = "."
                SQLInstanceName = "MSSQLSERVER"
                LoginType = "WindowsGroup"
            }

            xSQLServerRole "ServerRole$_" {
                DependsOn = @(("[xSQLServerLogin]Login" + $_))
                Ensure = "Present"
                Name = $_
                SQLServer = "."
                SQLInstanceName = "MSSQLSERVER"
                ServerRole = "sysadmin"
            } 
        }
```

I am deploying the new mof on the pull server and running `Update-DscConfiguration -Wait -Verbose`  on the client and seeing the following log statements for each server role I try to add:

```
VERBOSE: [TESTEZE-LJ6917L]: LCM:  [ Start  Resource ]  [[xSQLServerRole]ServerRoleEZETOP\Domain Admins]
VERBOSE: [TESTEZE-LJ6917L]: LCM:  [ Start  Test     ]  [[xSQLServerRole]ServerRoleEZETOP\Domain Admins]
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] Testing SQL roles for login EZETOP\Domain Admins
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] 2017-02-14_09-16-29: Connected to SQL .
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] Getting SQL Server roles for EZETOP\Domain Admins on SQL Server ..
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] 2017-02-14_09-16-29:  is absent in SQL role name sysadmin
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] 2017-02-14_09-16-29: String value for property Ensure does not match. Current state is 'Absent' and Desired state is
'Present'
VERBOSE: [TESTEZE-LJ6917L]: LCM:  [ End    Test     ]  [[xSQLServerRole]ServerRoleEZETOP\Domain Admins]  in 0.1430 seconds.
VERBOSE: [TESTEZE-LJ6917L]: LCM:  [ Start  Set      ]  [[xSQLServerRole]ServerRoleEZETOP\Domain Admins]
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] 2017-02-14_09-16-29: Connected to SQL .
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] Setting SQL Server roles for EZETOP\Domain Admins on SQL Server ..
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] 2017-02-14_09-16-29: Adding SQL login EZETOP\Domain Admins in role sysadmin
VERBOSE: [TESTEZE-LJ6917L]:                            [[xSQLServerRole]ServerRoleEZETOP\Domain Admins] 2017-02-14_09-16-29: SQL Roles for EZETOP\Domain Admins, successfullly added
VERBOSE: [TESTEZE-LJ6917L]: LCM:  [ End    Set      ]  [[xSQLServerRole]ServerRoleEZETOP\Domain Admins]  in 0.0560 seconds.
VERBOSE: [TESTEZE-LJ6917L]: LCM:  [ End    Resource ]  [[xSQLServerRole]ServerRoleEZETOP\Domain Admins]
```

(and I can see that the group was added to the role in SSMS).

I think you initially said that you could "crash the WMI" - how can you detect this?

As to your final question:
OS: 2012R2
WMF: 5.0
Sql Server 2012

**Comment by johlju** [comment] 2017-02-15 16:43
Ah there is a fix in the Dev version for this. Sorry, I should have started to ask what version of xSQLServer you were using. :/  I'm using the Dev version. Could you try the Dev version?

See the change log:
https://github.com/PowerShell/xSQLServer/blob/dev/CHANGELOG.md#unreleased

**Comment by johlju** [comment] 2017-02-15 16:49
It crashed the WMI literally. :) In the Application log.

```
Faulting application name: wmiprvse.exe, version: 10.0.10586.117, time stamp: 0x56bf015c
Faulting module name: ntdll.dll, version: 6.3.9600.17031, time stamp: 0x530895af
Exception code: 0xc0000374
Fault offset: 0x00000000000f8c9c
Faulting process id: 0xa4c
Faulting application start time: 0x01d286231c6c4e6c
Faulting application path: C:\Windows\system32\wbem\wmiprvse.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 5aaa5b58-f216-11e6-80ca-00505684ec39
Faulting package full name: 
Faulting package-relative application ID: 
```

**Closed** 2017-03-20 17:24 UTC
Labels: bug, help wanted

**Comment by johlju** [comment] 2017-03-21 19:37
@jrudley A new resource was merged into dev that hopefully will solve your problem.
