### ISSUE TITLE
xSqlServerSetup is missing after Importing the xSqlServer in the Azure Automation 

### ISSUE THREAD

**Issue by sujitks** [PowerShell/xSQLServer#833] opened 2017-09-20 07:33 UTC
**I have imported xSqlServer dsc module to my azure automation account and it only shows 26 modules, xSqlServerSetup is missing along with the xWaitForAvailabilityGroup:**

**It is a simple dsc configuration based on your example to install the sql server**

**I am trying to import xSqlServer 8.1.0.0 from the powershell gallery, I have tried importing from the azure module gallery as well with no success.**

**Comment by johlju** [comment] 2017-09-20 17:31
Duplicate of issue #713. Closing this issue.

**Closed by johlju** 2017-09-20 17:31 UTC
