### ISSUE TITLE
xSQLServerDatabase: Exception  calling "Create" with "0" argument(s)

### ISSUE THREAD

**Issue by Dalmirog** [PowerShell/xSQLServer#759] opened 2017-08-13 18:41 UTC
- Running configuration locally in push mode
- Windows 2016 server
- SQL server express 2014 installed in the same server
- If I try to create a DB by setting `ensure = present` I get `Exception  calling "Create" with "0" argument(s)`
- If I try to remove an existing DB setting `ensure = absent` I get `Exception  calling "Drop" with "0" argument(s)`
- If I run `ensure = present` for a DB that already exists, the configuration runs successfully
- I've check all the vent logs and the only error I can see is `Exception  calling "x" with "0" argument(s)`. But nowhere it tells me which arguments I'm missing :(

Script I'm using

```powershell
configuration DSCDatabase {

    Import-DscResource -ModuleName xSqlserver

    node localhost {
        xSQLServerDatabase "OctopusDatabase"{
         Name = 'DSCDatabase'
         SQLServer = $env:COMPUTERNAME
         SQLInstanceName = "SQLExpress"
         Ensure = 'present'
        }
    }
}

DSCDatabase -OutputPath $PSScriptRoot\DSCDatabase
Start-DscConfiguration $PSScriptRoot\DSCDatabase -Force -Wait
```

**Comment by Dalmirog** [comment] 2017-08-13 18:43
I also noticed that the example in your repo isn't using `$SysAdminAccount` even though the parameter is set as `Mandatory`.

https://github.com/PowerShell/xSQLServer/blob/dev/Examples/Resources/xSQLServerDatabase/1-CreateDatabase.ps1

**Comment by johlju** [comment] 2017-08-14 19:29
Can you run this and post the output?

```
$null = [System.Reflection.Assembly]::LoadWithPartialName('Microsoft.SqlServer.Smo')
$sqlDatabaseObject = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Database
$sqlDatabaseObject | gm | ? name -eq 'create'
```

_Submitted a new issue to track the problem with the example file._

**Comment by Dalmirog** [comment] 2017-08-14 20:11
Thanks for the response @johlju !

Output:

```
PS C:\Tools> $null = [System.Reflection.Assembly]::LoadWithPartialName('Microsoft.SqlServer.Smo')
$sqlDatabaseObject = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Database
$sqlDatabaseObject | gm | ? name -eq 'create'


   TypeName: Microsoft.SqlServer.Management.Smo.Database

Name   MemberType Definition                                                          
----   ---------- ----------                                                          
Create Method     void Create(bool forAttach), void Create(), void ICreatable.Create()



PS C:\Tools> 
```

**Comment by johlju** [comment] 2017-08-14 20:24
Okay, that looks good, so you got the type. And it should be able to call the Create() method. 
Not sure what's going on. 

Could you run this also
```
Get-Module *sql* -ListAvailable
```

**Comment by Dalmirog** [comment] 2017-08-14 20:25
```
PS C:\Tools> Get-Module *sql* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                  
---------- -------    ----                                ----------------                                  
Manifest   8.0.0.0    xSQLServer                                                                            


    Directory: C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                  
---------- -------    ----                                ----------------                                  
Manifest   1.0        SQLASCMDLETS                        {Add-RoleMember, Backup-ASDatabase, Invoke-ASCm...
Manifest   1.0        SQLPS                               {Backup-SqlDatabase, Add-SqlAvailabilityDatabas...


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager


ModuleType Version    Name                                ExportedCommands                                  
---------- -------    ----                                ----------------                                  
Manifest   2.1.0      AzureRM.Sql                         {Get-AzureRmSqlDatabaseRecommendedAction, Get-A...



PS C:\Tools> 
```

**Comment by Dalmirog** [comment] 2017-08-18 22:02
I ended up running this on another server, this time `Windows 2012`, and the same config worked. In this "new" VM I just installed SQL Express 2014 with tools from [Hanselman's post](https://www.hanselman.com/blog/DownloadSQLServerExpress.aspx).

So I went back to the 2016 VM were I initially ran the config (and failed), uninstalled everything related to SQL, and the installed SQL using the same MSI as for the 2012 VM. Then the config **worked**.

¯\_(ツ)_/¯

**Comment by johlju** [comment] 2017-08-19 09:26
@Dalmirog Sorry for not answering before, I was a lot stuff going on this week. I read the output above and didn't see any problems so I thought this should work. 
Could it be bad media (MSI) maybe? 

Happy you got it working! :smile: We file this one under "strange". Closing this issue. If you see this problem again, please reopen the issue.

**Closed by johlju** 2017-08-19 09:26 UTC
Labels: question

**Comment by DaniSQL** [comment] 2018-03-09 17:11
FYI - I hit this issue sporadically when somehow the service account didn't get enough permission in the data and log folders and database creation failed xSQLServerDatabase(it also failed from SSMS). I had to find what the issue is the hard way since the error didn't make sense to me

**Comment by johlju** [comment] 2018-03-12 17:50
@DaniSQL Thanks for sharing that! It will help the next person getting this error.

**Comment by jamesapicken** [comment] 2019-02-06 11:46
It definitely did help the next person getting this error...me! Thank you.

**Comment by cosminiv** [comment] 2020-05-19 12:26
I have run into the same error message. The actual cause was the fact that the db files already existed. After I deleted them I could create the db.
