### ISSUE TITLE
xSQLServerFailoverClusterSetup:  Resource looks for UpdateSource even when UpdateEnabled = false

### ISSUE THREAD

**Issue by aultt** [PowerShell/xSQLServer#399] opened 2017-02-22 16:13 UTC
**Details of the scenario you try and problem that is occurring:**
Providing Cluster configuration if UpdateEnabled = $false there is no need to look for UpdateSource
In my scenario the SQL Setup files are mounted to a VM. No update folder exists in the path because its an ISO.  Work around is to provide UpdateSource pointing to an empty location and configuration works.
**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Win2016, SQL 2016, PS 5.1
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
5.0.0.0

**Comment by johlju** [comment] 2017-02-22 17:34
Do you mean that when having `UpdateEnable = $false` in the configuration, the UpdateSource argument is added to the argument list when calling setup.exe?

**Comment by johlju** [comment] 2017-02-22 17:45
Could you please post the configuration with which you get the problem? Without any sensitive information.

**Comment by aultt** [comment] 2017-02-22 18:22
Hey Johlju with the latest code does xSQLServerSetup replace xSQLServerFailOverClusterSetup?

**Comment by johlju** [comment] 2017-02-22 18:38
Yes, it should be replaced by xSQLServerSetup. But use Dev version.

Any additions should be made to xSQLServerSetup. xSQLServerFailoverClusterSetupis deprecated and will be removed as soon as SSAS is confirmed working.

**Comment by johlju** [comment] 2017-02-22 18:39
Please try your configuration with xSQLServerSetup and submit any bugs you find. :)

**Comment by johlju** [comment] 2017-02-23 14:30
I close this issue since this resource is deprecated. If there is any further problems with this using xSQLServerSetup, then pleas re-open the issue.

**Closed by johlju** 2017-02-23 14:30 UTC
Labels: enhancement, help wanted, waiting for the author
