### ISSUE TITLE
Create AlwaysOn Endpoint - failed to connect to server....

### ISSUE THREAD

**Issue by Naboo2604** [PowerShell/xSQLServer#271] opened 2016-12-29 08:20 UTC
Hi All,

**Details of the scenario you try and problem that is occurring:**

i´m not sure if i have a mistake in my config, but i tried this many,many times with several changes in my config and failed every time with the same error in the same place. create of Cluster, install SQL instance, change AON setting in CL - everything works fine - exept the xSQLServerEndpoint creation.

VERBOSE: [SQL1]: LCM:  [ Start  Resource ]  [[xSQLServerEndpoint]SQL1]
VERBOSE: [SQL1]: LCM:  [ Start  Test     ]  [[xSQLServerEndpoint]SQL1]
VERBOSE: [SQL1]:                            [[xSQLServerEndpoint]SQL1] 2016-12-28_10-56-02: Connected to SQL SQL1
VERBOSE: [SQL1]: LCM:  [ End    Test     ]  [[xSQLServerEndpoint]SQL1]  in 21.5890 seconds.
VERBOSE: [SQL1]: LCM:  [ Start  Set      ]  [[xSQLServerEndpoint]SQL1]
VERBOSE: [SQL1]:                            [[xSQLServerEndpoint]SQL1] 2016-12-28_10-56-17: Connected to SQL SQL1
VERBOSE: [SQL1]:                            [[xSQLServerEndpoint]SQL1] Connected to Server
VERBOSE: [SQL1]:                            [[xSQLServerEndpoint]SQL1] Check to see login SG1\Administrator exist on the server
Exception calling "Contains" with "1" argument(s): "Failed to connect to server SQL1."
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : ConnectionFailureException
    + PSComputerName        : SQL1

[..]

**The DSC configuration that is using the resource (as detailed as possible):**

xSqlServerEndpoint $Node.NodeName
{
            Ensure              = 'Present'
            Port                = 5022
            AuthorizedUser      = 'SG1\Administrator'
            EndPointName        = 'Hadr_endpoint'
            DependsOn           = ('[xSqlServerSetup]' + $Node.NodeName)
            PsDscRunAsCredential = $Credential
}

SG1\Administrator is sysadmin in SQL instance (checked with sql studio) - PsDsCRunAs.. is also SG1\Administrator with the correct credentials - WinFirewall is off - SQL Instance is running - TCP is enabled and listening on all interfaces - AON is enabled in SQL Configuration - always receiving the same error...

other DscResources works fine (i.e xSqlServerAlwaysOnService, xSqlServerMaxDop, Memory,....)

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

Windows Server 2016 x64 GUI, SQL Server 2016 Enterprise and SQL Server 2014SP2 Ent. tested (same error) - us-en language and german keyboard...

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

4.0.0.0

..any help would be appreciated. 

many thanks in advance, Markus

**Comment by johlju** [comment] 2016-12-30 18:47
This in very odd. The other resources you say are working, they are using the same helper function to connect `Connect-SQL`.

I tested it now in my lab environment, but against SQL Server 2008 R2, and it works here at least. 
My environment is currently Windows Server 2012 R2, SQL Server 2008 R2 and PowerShell 5.0. And I do have a named instance. You seem to have a default instance, since you left out the parameters `SQLServer` and `SQLInstanceName`.

```
VERBOSE: [SQLTEST]: LCM:  [ Start  Resource ]  [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint]
VERBOSE: [SQLTEST]: LCM:  [ Start  Test     ]  [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint]
VERBOSE: [SQLTEST]:                            [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint] 2016-12-30_19-30-08: Connected to SQL SQLTEST\SQL2008R2
VERBOSE: [SQLTEST]: LCM:  [ End    Test     ]  [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint]  in 0.2500 seconds.
VERBOSE: [SQLTEST]: LCM:  [ Start  Set      ]  [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint]
VERBOSE: [SQLTEST]:                            [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint] 2016-12-30_19-30-08: Connected to SQL SQLTEST\SQL2008R2
VERBOSE: [SQLTEST]:                            [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint] Connected to Server
VERBOSE: [SQLTEST]:                            [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint] Check to see login COMPANY\sqlsvc exist on the server
VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]  [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint]  in 4.4030 seconds.
VERBOSE: [SQLTEST]: LCM:  [ End    Resource ]  [[xSQLServerEndpoint]SQL2008R2-MirrorEndpoint]
VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]
```

If you just run that resource in the configuration, does it throw the error still? Thinking that it might be something being configured before that is making it behave like this (long shoot though).

I need to setup a lab environment to test you configuration (Windows Server 2016 primarily) to verify this. See if I can reproduce the error. This is gonna take me a day or so to setup.

Would it be possible for you to give me the rest of your configuration (stripped of sensitive information)? At least the steps down to where 'xSqlServerEndpoint' is configured.  It would speed up my testing.

**Comment by Naboo2604** [comment] 2016-12-30 20:31
Hi Johan,

thank you for your reply - i used a named instance in my config - i extraced the mentioned parts from my config - that´s what i used as a test and failed:

```
configuration SQLAlwaysOnInstall
{
    Import-DscResource -ModuleName xSQLServer
    Import-DscResource -ModuleName xFailoverCluster
    Import-DscResource -ModuleName PSDesiredStateConfiguration

    # One can evaluate expressions to get the node list
    # E.g: $AllNodes.Where("Role -eq Web").NodeName
    node ("SQL1")
    {
        
        $SQLInstallUserName = $Node.ShortDomainName + "\" + $Node.SQLServiceAccount
        $AdminUserName = $Node.ShortDomainName + "\Administrator"

        $Credential = (Get-Credential -UserName $AdminUserName -Message "Credential for new VMs")
        $SQLServiceCredential = (Get-Credential -UserName $SQLInstallUserName -Message "SQL Installer Credentials")
        
        # Call Resource Provider
        # E.g: WindowsFeature, File
        WindowsFeature "NET" 
        {
           Ensure = "Present"
           Name   = "NET-Framework-Core"
        }
        WindowsFeature "ADTools" 
        {
           Ensure = "Present"
           Name   = "RSAT-AD-PowerShell"
        }
        xSqlServerSetup $Node.NodeName
        {
            SourcePath          = "C:\SQLSetup"
            Features            = "SQLENGINE"
            SQLSysAdminAccounts = $Node.ShortDomainName + "\" + $Node.SQLSysAdminAccounts
            InstallSharedDir    = "D:\Program Files\Microsoft SQL Server"
            InstallSharedWOWDir = "D:\Program Files (x86)\Microsoft SQL Server"
            InstanceDir         = "D:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Data"
            SQLUserDBDir        = "D:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Data"
            SQLUserDBLogDir     = "F:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Log"
            SQLTempDBDir        = "E:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Temp"
            SQLTempDBLogDir     = "F:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Log" 
            SQLBackupDir        = "F:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Backup"
            InstanceName        = $Node.InstanceName
            SetupCredential     = $Credential
            UpdateEnabled       = $Node.UpdateEnabled
            UpdateSource        = $Node.UpdateSource
            SQLSvcAccount       = $SQLServiceCredential
        }
        xSqlServerFirewall $Node.NodeName
        {
            SourcePath          = "C:\SQLSetup"
            InstanceName        = $Node.InstanceName
            Features            = "SQLENGINE"
            DependsOn           = ("[xSqlServerSetup]" + $Node.NodeName)
        }
        xSqlServerMemory $Node.NodeName
        {
            Ensure              = "Present"
            DynamicAlloc        = $True
            SQLInstanceName     = $Node.InstanceName
            DependsOn           = ("[xSqlServerSetup]" + $Node.NodeName)
        }
        xSqlServerMaxDop $Node.NodeName
        {
            Ensure              = "Present"
            DynamicAlloc        = $True
            SQLInstanceName     = $Node.InstanceName
            DependsOn           = ("[xSqlServerSetup]" + $Node.NodeName)
        }
        WindowsFeature FailoverFeature 
        {
            Ensure              = "Present"
            Name                = "Failover-Clustering"
            DependsOn           = ("[xSqlServerSetup]" + $Node.NodeName)
        }
        WindowsFeature RSATClusteringPowershell 
        {
            Ensure              = "Present"
            Name                = "RSAT-Clustering-Powershell"
            DependsOn           = "[WindowsFeature]FailoverFeature"
        }
        WindowsFeature RSATClusteringMgmt 
        {
            Ensure              = "Present"
            Name                = "RSAT-Clustering-Mgmt"
            DependsOn           = "[WindowsFeature]FailoverFeature"
        }
        WindowsFeature RSATClusteringCmdInterface 
        {
            Ensure              = "Present"
            Name                = "RSAT-Clustering-CmdInterface"
            DependsOn           = "[WindowsFeature]RSATClusteringPowershell"
        }
        xCluster ensureCreated 
        {
            Name                = $Node.ClusterName
            StaticIPAddress     = $Node.ClusterIPAddress
            DomainAdministratorCredential = $Credential
            DependsOn           = "[WindowsFeature]RSATClusteringCmdInterface"
        }
        xSqlServerAlwaysOnService $Node.NodeName 
        {
            Ensure              = "Present"
            DependsOn           = "[xCluster]ensureCreated",("[xSqlServerSetup]" + $Node.NodeName)
            SQLInstanceName     = $Node.InstanceName
            SQLServer           = $Node.Clustername
        }
        #until here it works!

        xSqlServerEndpoint $Node.NodeName
        {
            Ensure              = "Present"
            Port                = 5022
            AuthorizedUser      = "SG1\Administrator"
            EndPointName        = "Hadr_endpoint"
            DependsOn           = ("[xSqlServerSetup]" + $Node.NodeName)
            PsDscRunAsCredential = $Credential
        }
    }
}

SQLAlwaysOnInstall -OutputPath C:\Temp -ConfigurationData C:\Temp\SQLAlwaysOnInstall.psd1

```

```
@{
    AllNodes = @(
        @{
            NodeName            = "SQL1"
            Role                = "SQLPrimaryNode"
            PSDscAllowPLainTextPassword = $True
            ShortDomainName     = "SG1"
            DomainAdminName     = "Administrator"
            InstanceName        = "LyncCMS"
            SQLServiceAccount   = "_svc_sqlservice"
            UpdateEnabled       = $True
	    UpdateSource        = "C:\SQLSetup\Source\Updates"
            SQLSysAdminAccounts = "_lgSQLAdmins"
            ClusterName         = "SQLCL"
            ClusterIPAddress    = "10.0.0.10/24"
            AvailabilityGroup   = "AGSfB"                             # max. 20 Characters!
            AGIPAddress         = "10.0.0.14/255.255.255.0"
            AGPort              = 5031
            }
    )
}
```
...something is redundant, it´s from the testing - but i think this config should generally work?

If i start this DSC on a plain new VM with SQL2016 Sources it fails with the error:

```
{"time": "2016-12-30T21:11:37.897+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Start  Resource ]  [[xCluster]ensureCreated]  "},
  {"time": "2016-12-30T21:11:37.897+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Start  Test     ]  [[xCluster]ensureCreated]  "},
  {"time": "2016-12-30T21:11:37.904+01:00", "type": "verbose", "message": "[SQL1]:                            [[xCluster]ensureCreated] Checking if Cluster SQLCL is present ..."},
  {"time": "2016-12-30T21:11:37.967+01:00", "type": "verbose", "message": "[SQL1]:                            [[xCluster]ensureCreated] Enumerating clusters in domain sg1.airforce.mil."},
  {"time": "2016-12-30T21:11:38.003+01:00", "type": "verbose", "message": "[SQL1]:                            [[xCluster]ensureCreated] Cluster SQLCL is present"},
  {"time": "2016-12-30T21:11:38.003+01:00", "type": "verbose", "message": "[SQL1]:                            [[xCluster]ensureCreated] Checking if the node is in cluster SQLCL ..."},
  {"time": "2016-12-30T21:11:38.050+01:00", "type": "verbose", "message": "[SQL1]:                            [[xCluster]ensureCreated] Node is in cluster SQLCL"},
  {"time": "2016-12-30T21:11:38.050+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ End    Test     ]  [[xCluster]ensureCreated]  in 0.1530 seconds."},
  {"time": "2016-12-30T21:11:38.050+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Skip   Set      ]  [[xCluster]ensureCreated]  "},
  {"time": "2016-12-30T21:11:38.051+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ End    Resource ]  [[xCluster]ensureCreated]  "},
  {"time": "2016-12-30T21:11:38.054+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Start  Resource ]  [[xSQLServerAlwaysOnService]SQL1]  "},
  {"time": "2016-12-30T21:11:38.054+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Start  Test     ]  [[xSQLServerAlwaysOnService]SQL1]  "},
  {"time": "2016-12-30T21:11:38.068+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLServerAlwaysOnService]SQL1] 2016-12-30_21-11-38: Connected to SQL SQLCL\\LyncCMS"},
  {"time": "2016-12-30T21:11:38.158+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLServerAlwaysOnService]SQL1] 2016-12-30_21-11-38: SQL Always On is enabled on \"SQLCL\\LyncCMS\"."},
  {"time": "2016-12-30T21:11:38.159+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLServerAlwaysOnService]SQL1] 2016-12-30_21-11-38: SQL Always On is in the desired state for \"SQLCL\\LyncCMS\": True."},
  {"time": "2016-12-30T21:11:38.161+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ End    Test     ]  [[xSQLServerAlwaysOnService]SQL1]  in 0.1040 seconds."},
  {"time": "2016-12-30T21:11:38.161+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Skip   Set      ]  [[xSQLServerAlwaysOnService]SQL1]  "},
  {"time": "2016-12-30T21:11:38.161+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ End    Resource ]  [[xSQLServerAlwaysOnService]SQL1]  "},
  {"time": "2016-12-30T21:11:38.161+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Start  Resource ]  [[xSQLServerEndpoint]SQL1]  "},
  {"time": "2016-12-30T21:11:38.162+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Start  Test     ]  [[xSQLServerEndpoint]SQL1]  "},
  {"time": "2016-12-30T21:11:38.186+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLServerEndpoint]SQL1] 2016-12-30_21-11-38: Connected to SQL SQL1"},
  {"time": "2016-12-30T21:11:52.812+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ End    Test     ]  [[xSQLServerEndpoint]SQL1]  in 14.6520 seconds."},
  {"time": "2016-12-30T21:11:52.812+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ Start  Set      ]  [[xSQLServerEndpoint]SQL1]  "},
  {"time": "2016-12-30T21:11:52.823+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLServerEndpoint]SQL1] 2016-12-30_21-11-52: Connected to SQL SQL1"},
  {"time": "2016-12-30T21:11:52.823+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLServerEndpoint]SQL1] Connected to Server"},
  {"time": "2016-12-30T21:11:52.825+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLServerEndpoint]SQL1] Check to see login SG1\Administrator exist on the server"},
  {"time": "2016-12-30T21:11:52.957+01:00", "type": "error", "message": "Exception calling \"Contains\" with \"1\" argument(s): \"Failed to connect to server SQL1.\""},
  {"time": "2016-12-30T21:11:52.975+01:00", "type": "error", "message": "Exception calling \".ctor\" with \"2\" argument(s): \"SetParent failed for Endpoint 'Hadr_endpoint'. \""},
  {"time": "2016-12-30T21:11:52.979+01:00", "type": "error", "message": "The property 'EndpointType' cannot be found on this object. Verify that the property exists and can be set."},
  {"time": "2016-12-30T21:11:52.982+01:00", "type": "error", "message": "The property 'ProtocolType' cannot be found on this object. Verify that the property exists and can be set."},
  {"time": "2016-12-30T21:11:52.987+01:00", "type": "error", "message": "The property 'ListenerPort' cannot be found on this object. Verify that the property exists and can be set."},
  {"time": "2016-12-30T21:11:52.993+01:00", "type": "error", "message": "The property 'ServerMirroringRole' cannot be found on this object. Verify that the property exists and can be set."},
  {"time": "2016-12-30T21:11:52.996+01:00", "type": "error", "message": "The property 'EndpointEncryption' cannot be found on this object. Verify that the property exists and can be set."},
  {"time": "2016-12-30T21:11:52.999+01:00", "type": "error", "message": "The property 'EndpointEncryptionAlgorithm' cannot be found on this object. Verify that the property exists and can be set."},
  {"time": "2016-12-30T21:11:53.002+01:00", "type": "error", "message": "You cannot call a method on a null-valued expression."},
  {"time": "2016-12-30T21:11:53.006+01:00", "type": "error", "message": "You cannot call a method on a null-valued expression."},
  {"time": "2016-12-30T21:11:53.009+01:00", "type": "error", "message": "You cannot call a method on a null-valued expression."},
  {"time": "2016-12-30T21:11:53.013+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ End    Set      ]  [[xSQLServerEndpoint]SQL1]  in 0.2010 seconds."},
  {"time": "2016-12-30T21:11:53.013+01:00", "type": "error", "message": "The PowerShell DSC resource '[xSQLServerEndpoint]SQL1' with SourceInfo 'C:\\ClusterStorage\\HV-Data1\\Lability\\Configurations\\Lync2013vLab.ps1::696::9::xSQLServerEndpoint' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details."},
  {"time": "2016-12-30T21:11:53.014+01:00", "type": "verbose", "message": "[SQL1]:                            [] Consistency check completed."}
```
..crazy thing is that i.e xSQLServerAlwaysOnService a little before the Endpoint section work´s fine - and can connect to SQL - but Endpoint Resource can not. 
I also tried this with and without the parameter "AuthorizedUser" in the Endpoint section (in this case SG1\Administrator is the Domain Admin with the correct credentials and it has the sysadmin role within the LyncCMS instance)

you say you tried it with sql 2008r2 - maybe there is a difference between endpoint creation in sql 2008r2 and 2014/2016 (because in 2008r2 was no alwayson feature available)?

thank´s for your help.

greetings, Markus

**Comment by johlju** [comment] 2016-12-31 13:52
I provisioned a lab server with Windows Server 2016 and SQL Server 2014. And I throw your configuration at it, and it all worked. I did some minor adjustments though, but that could be changes you made during your testing.
If you make these changes, what happens for you?

* For the resource xSQLServerAlwaysOnService I had to change to this `SQLServer = $Node.NodeName`. 
* For the resource xSQLServerEndpoint I had to add `SQLInstanceName = $Node.InstanceName`.

_Also made following changes, but should not make a difference_
* _For the resource xSQLServerSetup i removed the parameters `UpdateEnabled` and `UpdateSource`, but that was just so I didn't have to set up that too. Also changed all the paths to the C: drive_
* _Used a certificate to encrypt the credential objects._

Happy new year!!! 🎆 

Verbose output as follows
```powershell
VERBOSE: [SQLTEST4]: LCM:  [ Start  Resource ]  [[xSQLServerEndpoint]sqltest4.company.local]
VERBOSE: [SQLTEST4]: LCM:  [ Start  Test     ]  [[xSQLServerEndpoint]sqltest4.company.local]
VERBOSE: [SQLTEST4]:                            [[xSQLServerEndpoint]sqltest4.company.local] 2016-12-31_14-17-05: Connected to SQL SQLTEST4\SQL2014
VERBOSE: [SQLTEST4]: LCM:  [ End    Test     ]  [[xSQLServerEndpoint]sqltest4.company.local]  in 1.0000 seconds.
VERBOSE: [SQLTEST4]: LCM:  [ Start  Set      ]  [[xSQLServerEndpoint]sqltest4.company.local]
VERBOSE: [SQLTEST4]:                            [[xSQLServerEndpoint]sqltest4.company.local] 2016-12-31_14-17-05: Connected to SQL SQLTEST4\SQL2014
VERBOSE: [SQLTEST4]:                            [[xSQLServerEndpoint]sqltest4.company.local] Connected to Server
VERBOSE: [SQLTEST4]:                            [[xSQLServerEndpoint]sqltest4.company.local] Check to see login COMPANY\sqladm exist on the server
VERBOSE: [SQLTEST4]: LCM:  [ End    Set      ]  [[xSQLServerEndpoint]sqltest4.company.local]  in 4.6210 seconds.
VERBOSE: [SQLTEST4]: LCM:  [ End    Resource ]  [[xSQLServerEndpoint]sqltest4.company.local]
```

SQLAlwaysOnConfig.ps1
```
Configuration SQLAlwaysOnInstall
{
    Import-DscResource -ModuleName xSQLServer
    Import-DscResource -ModuleName xFailoverCluster
    Import-DscResource -ModuleName PSDesiredStateConfiguration

    Node ('sqltest4.company.local')
    {
        # ... UNCHANGED CODE REMOVED

        xSqlServerSetup $Node.NodeName
        {
            SourcePath          = "C:\SQLSetup"
            Features            = "SQLENGINE"
            SQLSysAdminAccounts = $Node.ShortDomainName + "\" + $Node.SQLSysAdminAccounts
            InstallSharedDir    = "C:\Program Files\Microsoft SQL Server"
            InstallSharedWOWDir = "C:\Program Files (x86)\Microsoft SQL Server"
            InstanceDir         = "C:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Data"
            SQLUserDBDir        = "C:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Data"
            SQLUserDBLogDir     = "C:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Log"
            SQLTempDBDir        = "C:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Temp"
            SQLTempDBLogDir     = "C:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Log" 
            SQLBackupDir        = "C:\MSSQL13." + ($Node.InstanceName) + "\MSSQL\Backup"
            InstanceName        = $Node.InstanceName
            SetupCredential     = $Credential
            #UpdateEnabled       = $Node.UpdateEnabled
            #UpdateSource        = $Node.UpdateSource
            SQLSvcAccount       = $SQLServiceCredential
        }

        # ... UNCHANGED CODE REMOVED
       
        xSqlServerAlwaysOnService $Node.NodeName 
        {
            Ensure              = "Present"
            DependsOn           = "[xCluster]ensureCreated",("[xSqlServerSetup]" + $Node.NodeName)
            SQLInstanceName     = $Node.InstanceName
            SQLServer           = $Node.NodeName #Clustername
        }

        xSqlServerEndpoint $Node.NodeName
        {
            Ensure              = "Present"
            SQLInstanceName     = $Node.InstanceName
            Port                = 5022
            AuthorizedUser      = $AdminUserName
            EndPointName        = "Hadr_endpoint"
            DependsOn           = ("[xSqlServerSetup]" + $Node.NodeName)
            PsDscRunAsCredential = $Credential
        }
    }
}

SQLAlwaysOnInstall -OutputPath C:\DSCTemp -ConfigurationData C:\DSCTemp\SQLAlwaysOnInstall.psd1 -Verbose

Start-DscConfiguration -Path "C:\DSCTemp" -ComputerName 'sqltest4.company.local' -Wait -Verbose -Force 
```

SQLAlwaysOnInstall.psd1
```powershell
@{
    AllNodes = @(
        @{
            NodeName             = "sqltest4.company.local"
            Guid                 = 'f431da94-78a9-471a-b6b8-f12646f4dda4'
            PSDscAllowDomainUser = $true
            CertificateFile      = 'C:\DSCTemp\dsc-config.company.local.cer'

            Role                 = "SQLPrimaryNode"
            ShortDomainName      = "COMPANY"
            DomainAdminName      = "sqladm"
            InstanceName         = "SQL2014"
            SQLServiceAccount    = "svcsql"
            SQLSysAdminAccounts  = 'SQLAdmins'
            ClusterName          = "TESTCLU4"
            ClusterIPAddress     = "192.168.0.10/24"
            AvailabilityGroup    = "TESTCLU4-AG"
            AGIPAddress          = "192.168.0.11/255.255.255.0"
            AGPort               = 5304
            #UpdateEnabled       = $True
            #UpdateSource        = "C:\SQLSetup\Source\Updates"

            #PSDscAllowPLainTextPassword = $True
        }
    )
}
```

**Comment by Naboo2604** [comment] 2017-01-01 15:35
Hi Johan,
thank you for testing this in your env and your changes to the config files - based on your changes i made the following modifications in my environment and now this resource work:

- first i changed the clear-text-pwds to certificate based as yours
- changed sqlserver and add sqlserverinstance parameters in both sections
- changed from "simple" naming SQL1 (NodeName) to fqdn because you used it in your config (tried this with and without fqdn - whatever used both types works)

not sure what from the above are the solution but now xSQLServerEndpoint are working as expected.

while testing a idea was also the permission of my SQL service account - in my case this service account does NOT have local admin priviledges on my sql server - does your user "svcsql" have local admin rights on sqltest4 ?

another interesting "problem" arises after solving the xSQLServerEndpoint error - the next DSC resource in my script should create the AON group with xSQLAOGroupEnsure - this give´s me the idea with the local admin permission - in my case it failed with error:

```
  {"time": "2017-01-01T16:22:27.986+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] Loading module from path 'D:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\SQLPS\\Microsoft.SqlServer.Management.PSSnapins.dll'."},
  {"time": "2017-01-01T16:22:27.986+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] Loading module from path 'D:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\SQLPS\\Microsoft.SqlServer.Management.PSProvider.dll'."},
  {"time": "2017-01-01T16:22:27.987+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] Loading module from path 'D:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\SQLPS\\SqlPsPostScript.ps1'."},
  {"time": "2017-01-01T16:22:28.128+01:00", "type": "verbose", "message": "[SQL1]: LCM:  [ End    Set      ]  [[xSQLAOGroupEnsure]SQL1]  in 10.1270 seconds."},
  {"time": "2017-01-01T16:22:28.128+01:00", "type": "error", "message": "PowerShell DSC resource MSFT_xSQLAOGroupEnsure  failed to execute Set-TargetResource functionality with error message: Failed to Create SfBAON in OU=Servers,OU=Resources,DC=sg1,DC=airforce,DC=mil "},
  {"time": "2017-01-01T16:22:28.237+01:00", "type": "verbose", "message": "[SQL1]:                            [] Consistency check completed."}
```

...i don´t know what account this resource are using for creating the vCO in AD, if it is the SQLserviceaccount this error is correct, because in my case the SQLservice account does not have DomainAdmin permissions - it could not be the user of the PsDscRunAs parameter and not the account from SetupCredential parameter (tried both as DomainAdmin) because in my case $Credential IS the DomainAdmin account - my config:

```
                xSQLAOGroupEnsure ($Node.NodeName) 
                {
                  Ensure = "Present"
                  SQLInstanceName = $Node.InstanceName
                  EndPointPort = 5022
                  AvailabilityGroupName = "SkypeForBusinessAON"
                  AvailabilityGroupNameListener = "SfBAON"
                  AvailabilityGroupNameIP = "10.0.0.13"
                  AvailabilityGroupSubMask ="255.255.255.0"
                  SetupCredential = $SQLServiceCredential
                  PsDscRunAsCredential = $Credential
                  DependsOn = ("[xSQLServerEndpoint]" + $Node.NodeName),("[xSQLServerAlwaysOnService]" + $Node.NodeName)
               }
```

i will make further tests with this config and post updates in this thread for anyone who have the same troubles.

thank you again for your help and a happy new year 2017!
greets, Markus

**Comment by Naboo2604** [comment] 2017-01-01 15:53
..in addition to my last post - for testing purposes i added my SQLServiceAccount "_svc_sqlservice" to the Domain Admin Group - and voila the xSQLAOGroupEnsure can create the vCO in AD:

```
  {"time": "2017-01-01T16:42:07.486+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] Loading module from path 'D:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\SQLPS\\Sqlps.ps1'."},
  {"time": "2017-01-01T16:42:07.487+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] Loading module from path 'D:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\SQLPS\\Microsoft.SqlServer.Management.PSSnapins.dll'."},
  {"time": "2017-01-01T16:42:07.488+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] Loading module from path 'D:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\SQLPS\\Microsoft.SqlServer.Management.PSProvider.dll'."},
  {"time": "2017-01-01T16:42:07.489+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] Loading module from path 'D:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\SQLPS\\SqlPsPostScript.ps1'."},
  {"time": "2017-01-01T16:42:08.520+01:00", "type": "verbose", "message": "[SQL1]:                            [[xSQLAOGroupEnsure]SQL1] 2017-01-01_16-42-08: Created Computer Object SfBAON"},
```
...that means - independent of the PsDscRunAsCredential or the SetupCredential parameters in xSQLAOGroupEnsure:

```
                xSQLAOGroupEnsure ($Node.NodeName) 
                {
                  Ensure = "Present"
                  SQLInstanceName = $Node.InstanceName
                  EndPointPort = 5022
                  AvailabilityGroupName = "SkypeForBusinessAON"
                  AvailabilityGroupNameListener = "SfBAON"
                  AvailabilityGroupNameIP = "10.0.0.13"
                  AvailabilityGroupSubMask ="255.255.255.0"
                  SetupCredential = $SQLServiceCredential
                  PsDscRunAsCredential = $Credential
                  DependsOn = ("[xSQLServerEndpoint]" + $Node.NodeName),("[xSQLServerAlwaysOnService]" + $Node.NodeName)
               }
```


...within the resource the _svc_sqlservice account are used for some tasks?!

maybe this could also have been the problem with the xSQLServerEndpoint??

**Comment by johlju** [comment] 2017-01-02 16:43
Glad it worked out for you with xSQLServerEndpoint! 
My SQL Service account is not local admin on the server. It is just a regular domain user.

It is when the the listener is created as the VCO is created and AD. And normally it should be the CNO that creates this object. As the resource xSQLServerAvailabilityGroupListener does. 

>xSQLServerAvailabilityGroupListener 
>This resource requires that the CNO has been delegated the right Create computer object on the organizational unit (OU) in which the CNO resides.

Unfortunately the resource xSQLAOGroupEnsure has been written in a way that "forces" the VCO in AD with the credentials you provided in `SetupCredential` is used to create a computer object in AD. That is why you also need the Active Directory Module which you normally shouldn't need to have installed.
There are issues (#236 and #237) pending to replace this resource.

But with that said, the credentials you provided in `SetupCredential` should just need to have the right Create Computer Object in the OU where the CNO resides.

Hope this helped.

**Comment by johlju** [comment] 2017-01-10 15:22
@Naboo2604 I missed the last question in your last comment, sorry!

xSQLServerEndpoint should only work when the `PsDscRunAsCredential` parameter is set to a account with the permission to enumerate logins, create the endpoint, and set the permission on that endpoint.

I will add this to the readme and after that I will close this issue. Please feel free to reopen and comment further if you need any more help regarding this issue.

**Closed** 2017-01-12 15:24 UTC
Labels: help wanted, question
